version: '3.8'

services:
  mybb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ${PWD}/mybb:/var/www/html:rw

  nginx:
    image: nginx:mainline-alpine
    ports:
    - published: 8090
      target: 80
    volumes:
    - ${PWD}/nginx:/etc/nginx/conf.d:ro
    - ${PWD}/mybb:/var/www/html:ro

  postgresql:
    environment:
      POSTGRES_DB: mybb
      POSTGRES_PASSWORD: mybbpassword
      POSTGRES_USER: mybb
    image: postgres:13.2-alpine
    ports:
    - published: 5432
      target: 5432
    volumes:
    - ${PWD}/postgres/data:/var/lib/postgresql/data:rw
