version: '3.8'

services:
  mybb:
    image: mybb/mybb:latest
    volumes:
    - ${PWD}/mybb:/var/www/html:rw

  nginx:
    image: nginx:mainline-alpine
    ports:
    - published: 8090
      target: 80
    volumes:
    - ${PWD}/nginx:/etc/nginx/conf.d:ro
    - ${PWD}/mybb:/var/www/html:ro

  mysql:
    environment:
      MYSQL_DATABASE: mybb
      MYSQL_ROOT_PASSWORD: mybbpasswordroot
      MYSQL_USER: mybb
      MYSQL_PASSWORD: mybbpassword
    image: mysql:8.0
    ports:
    - published: 3306
      target: 3306
    volumes:
    - /var/lib/mysql/data:/var/lib/mysql/data:rw
